CREATE TABLE IF NOT EXISTS email_templates (
  id int(11) NOT NULL AUTO_INCREMENT,
  codigo varchar(50) NOT NULL,
  nombre varchar(100) NOT NULL,
  asunto varchar(200) NOT NULL,
  cuerpo_html text NOT NULL,
  variables_disponibles text DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (id),
  UNIQUE KEY uk_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO email_templates (codigo, nombre, asunto, cuerpo_html, variables_disponibles) VALUES
('welcome_usuario', 'Bienvenida Usuario', 'Bienvenido a Kimi', '<p>Hola <strong style=\"color:#ffffff\">{{nombre}}</strong>,</p><p>Tu cuenta ha sido creada exitosamente. Estos son tus datos:</p><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#0f0f1a;border-radius:12px;padding:16px;margin:16px 0\"><tr><td style=\"color:#9ca3af;padding:4px 0\">Email:</td><td style=\"color:#ffffff;padding:4px 0;font-weight:600\">{{email}}</td></tr></table><p>Con tu cuenta puedes:</p><ul style=\"color:#d1d5db;padding-left:20px\"><li>Guardar escorts en favoritos</li><li>Dejar valoraciones y comentarios</li><li>Recibir notificaciones de tus escorts favoritas</li></ul><p style=\"margin-top:20px\">Explora nuestro directorio y encuentra la compañía perfecta para ti.</p>', '{\"nombre\": \"Nombre del usuario\", \"email\": \"Correo electrónico\"}'),
('welcome_escort', 'Bienvenida Escort', 'Bienvenida a Kimi - Panel de Escort', '<p>Hola <strong style=\"color:#ffffff\">{{nombre}}</strong>,</p><p>Tu cuenta de escort ha sido creada exitosamente. Tus datos de acceso:</p><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#0f0f1a;border-radius:12px;padding:16px;margin:16px 0\"><tr><td style=\"color:#9ca3af;padding:4px 0\">Email:</td><td style=\"color:#ffffff;padding:4px 0;font-weight:600\">{{email}}</td></tr></table><p>Pasos para comenzar:</p><ol style=\"color:#d1d5db;padding-left:20px\"><li>Completa tu perfil (fotos, descripción, servicios)</li><li>Selecciona un plan de suscripción</li><li>Espera la aprobación del administrador</li><li>Una vez aprobada, tu anuncio estará visible</li></ol><p style=\"margin-top:20px\">Ingresa a tu panel desde <a href=\"{{site_url}}/micuenta/login\" style=\"color:#ef4444;text-decoration:none;font-weight:600\">{{site_url}}/micuenta/login</a></p>', '{\"nombre\": \"Nombre de la escort\", \"email\": \"Correo electrónico\", \"site_url\": \"URL del sitio\"}'),
('recovery', 'Recuperación de Contraseña', 'Recuperación de Contraseña', '<p>Recibimos una solicitud para restablecer tu contraseña.</p><p style=\"text-align:center;margin:32px 0\"><a href=\"{{reset_url}}\" style=\"display:inline-block;background:linear-gradient(135deg,#ef4444,#dc2626);color:#ffffff;padding:14px 32px;border-radius:12px;text-decoration:none;font-weight:700;font-size:16px\">Restablecer Contraseña</a></p><p style=\"color:#9ca3af;font-size:13px\">Este enlace expira en 1 hora. Si no solicitaste este cambio, ignora este correo.</p><p style=\"color:#9ca3af;font-size:13px\">Si el botón no funciona, copia y pega este enlace en tu navegador:</p><p style=\"color:#6b7280;font-size:12px;word-break:break-all\">{{reset_url}}</p>', '{\"reset_url\": \"Enlace para restablecer\", \"site_url\": \"URL del sitio\"}'),
('password_changed', 'Contraseña Actualizada', 'Contraseña Actualizada', '<p>Hola <strong style=\"color:#ffffff\">{{nombre}}</strong>,</p><p>Tu contraseña ha sido cambiada exitosamente.</p><p>Si no realizaste este cambio, contacta al soporte de inmediato.</p>', '{\"nombre\": \"Nombre del usuario/escort\"}'),
('verificacion_aprobada', 'Verificación Aprobada', 'Verificación Aprobada - Kimi', '<p>Hola <strong style=\"color:#ffffff\">{{nombre}}</strong>,</p><p>Tu verificación de identidad ha sido <strong style=\"color:#22c55e\">aprobada</strong>.</p><p>Ahora cuentas con el badge de verificación en tu perfil, lo que genera mayor confianza en los clientes.</p>', '{\"nombre\": \"Nombre de la escort\"}'),
('verificacion_rechazada', 'Verificación Rechazada', 'Verificación Rechazada - Kimi', '<p>Hola <strong style=\"color:#ffffff\">{{nombre}}</strong>,</p><p>Tu verificación de identidad ha sido <strong style=\"color:#ef4444\">rechazada</strong>.</p><p><strong style=\"color:#fbbf24\">Motivo:</strong> {{motivo}}</p><p>Puedes volver a intentarlo subiendo una nueva foto desde tu panel.</p>', '{\"nombre\": \"Nombre de la escort\", \"motivo\": \"Motivo del rechazo\"}')
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), asunto=VALUES(asunto), cuerpo_html=VALUES(cuerpo_html), variables_disponibles=VALUES(variables_disponibles);
